# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
